
CREATE   VIEW   HBC_APP_UAT_VIEW.V_SAKS_PROMO_STORE_DAY
 AS 
LOCKING ROW FOR ACCESS 

SELECT  

      SKIN_NO_UPC 
      ,DEPT 
      ,STR
      ,STORE_NBR
      ,STORE_ID
      ,CLASS_1
      ,TRAN_NO
      ,QUANTITY
      , RETUN_SALE
      , POLICY_CREDIT
      , COUPON_MD
      , SALES_RETAIL
      , EMP_DISC
,DAY_ID

  ,  CRTD_DATE
    
    ,CAST((CRTD_DATE) AS DATE FORMAT 'YYMMDD') DAY_DT
    
      , PROMO_MD
      --, SUBSTR(TRIM(SLS_BOGO_COUPON_NO), CHARACTER(TRIM(SLS_BOGO_COUPON_NO))-4) BOGO_COUPON
      , BOGO_COUPON
       , SALES_EMP_ID
       
      , TERMINAL
       ,TRIM(CRTD_DATE) ||'-'|| TRIM(SKIN_NO_UPC)||'-'|| TRIM(DEPT) ||'-'|| TRIM(STR)  BOGO_DATA

     
FROM  

        HBC_sit.SAKS_COUPONS_DETAIL A     
        
    JOIN HBC_APP_VIEW.V_TM_DAY B
    
    ON CAST((A.CRTD_DATE) AS DATE FORMAT 'YYMMDD') =B.DAY_DT
    WHERE STORE_NBR IS NOT NULL;



CREATE  VIEW   HBC_APP_UAT_VIEW.V_SAKS_PROMO_COUPON_DETAILS
 AS 
LOCKING ROW FOR ACCESS 

SELECT
 COUPON_ID 
      ,BANNER 
   ,   COUPON_TYPE 
    ,  COUPON_DISCOUNT 
    ,  COUPON_AMOUNT
    ,  COUPON_NBR 
    ,  TRIM(COUPON_BAR_CODE) BOGO_COUPON
    ,  COUPON_DESCRIPTION 
    ,  COUPON_EFF_DATE


FROM  HBC_SIT.SAKS_COUPONS


